app = "status-app-agent"
primary_region = "arn"

[build]
  dockerfile = "grafana-agent/Dockerfile"
  build_target = ""
  [build.args]

[env]
  # Will be set via secrets

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
